//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUIs.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue the transaction?.
        /// </summary>
        internal static string confirmation_txt1 {
            get {
                return ResourceManager.GetString("confirmation_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter PIN.
        /// </summary>
        internal static string confirmPass_txt1 {
            get {
                return ResourceManager.GetString("confirmPass_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Press Enter to accept, Clear to re-enter).
        /// </summary>
        internal static string confirmPass_txt2 {
            get {
                return ResourceManager.GetString("confirmPass_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Press Cancel to cancel).
        /// </summary>
        internal static string confirmPass_txt3 {
            get {
                return ResourceManager.GetString("confirmPass_txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the current PIN.
        /// </summary>
        internal static string doiPin_txt1 {
            get {
                return ResourceManager.GetString("doiPin_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your PIN code then press ENTER.
        /// </summary>
        internal static string enterPin_txt1 {
            get {
                return ResourceManager.GetString("enterPin_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Mind using your hand to hide the keyboard avoid being exposed PIN code).
        /// </summary>
        internal static string enterPin_txt2 {
            get {
                return ResourceManager.GetString("enterPin_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        internal static string enterPin_txt3 {
            get {
                return ResourceManager.GetString("enterPin_txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to cancel.
        /// </summary>
        internal static string enterPin_txt4 {
            get {
                return ResourceManager.GetString("enterPin_txt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the transaction.
        /// </summary>
        internal static string feature_txt1 {
            get {
                return ResourceManager.GetString("feature_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        internal static string feature_txt2 {
            get {
                return ResourceManager.GetString("feature_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfering.
        /// </summary>
        internal static string feature_txt3 {
            get {
                return ResourceManager.GetString("feature_txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string feature_txt4 {
            get {
                return ResourceManager.GetString("feature_txt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print statics.
        /// </summary>
        internal static string feature_txt5 {
            get {
                return ResourceManager.GetString("feature_txt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PIN.
        /// </summary>
        internal static string feature_txt6 {
            get {
                return ResourceManager.GetString("feature_txt6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press.
        /// </summary>
        internal static string fee_cancelLeft {
            get {
                return ResourceManager.GetString("fee_cancelLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to cancel.
        /// </summary>
        internal static string fee_cancelRight {
            get {
                return ResourceManager.GetString("fee_cancelRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        internal static string fee_enterLeft {
            get {
                return ResourceManager.GetString("fee_enterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to continue.
        /// </summary>
        internal static string fee_enterRight {
            get {
                return ResourceManager.GetString("fee_enterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIDV notify you about fee of transaction executing on ATM.
        /// </summary>
        internal static string fee_txt1 {
            get {
                return ResourceManager.GetString("fee_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee of drawing.
        /// </summary>
        internal static string fee_txt2 {
            get {
                return ResourceManager.GetString("fee_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee of transfering.
        /// </summary>
        internal static string fee_txt3 {
            get {
                return ResourceManager.GetString("fee_txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee of printing bill.
        /// </summary>
        internal static string fee_txt4 {
            get {
                return ResourceManager.GetString("fee_txt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 vnd/ transaction ( apply from 15/09/2016).
        /// </summary>
        internal static string fee_txt5 {
            get {
                return ResourceManager.GetString("fee_txt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.05% money transered, minimum 2000 vnd, maximum 20000 vnd.
        /// </summary>
        internal static string fee_txt6 {
            get {
                return ResourceManager.GetString("fee_txt6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Fee not including 10% VAT.
        /// </summary>
        internal static string fee_txt7 {
            get {
                return ResourceManager.GetString("fee_txt7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 vnd/transaction.
        /// </summary>
        internal static string fee_txt8 {
            get {
                return ResourceManager.GetString("fee_txt8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to print bill?.
        /// </summary>
        internal static string in_txt1 {
            get {
                return ResourceManager.GetString("in_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction is being executed.
        /// </summary>
        internal static string loading_txt1 {
            get {
                return ResourceManager.GetString("loading_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string loading_txt2 {
            get {
                return ResourceManager.GetString("loading_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new PIN.
        /// </summary>
        internal static string newPass_txt1 {
            get {
                return ResourceManager.GetString("newPass_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter account number received money.
        /// </summary>
        internal static string nhapSTK_txt1 {
            get {
                return ResourceManager.GetString("nhapSTK_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfering account number.
        /// </summary>
        internal static string nhapSTK_txt2 {
            get {
                return ResourceManager.GetString("nhapSTK_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving account number.
        /// </summary>
        internal static string nhapSTK_txt3 {
            get {
                return ResourceManager.GetString("nhapSTK_txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER NUMBER.
        /// </summary>
        internal static string rutTien_txt1 {
            get {
                return ResourceManager.GetString("rutTien_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL THE TRANSACTION.
        /// </summary>
        internal static string rutTien_txt2 {
            get {
                return ResourceManager.GetString("rutTien_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the money.
        /// </summary>
        internal static string soTienChuyen_txt1 {
            get {
                return ResourceManager.GetString("soTienChuyen_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEFORE EXECUTING TRANSACTION YOU SHOULD
        ///- Observe ATM machine carefully to detect the machine appended device stealing data. Especially note something following (picture below)
        ///1. ATM keyboard
        ///2.Head reader
        ///3.Location of camera to steal Pin code
        ///4.Coat of ATM machine
        ///- Don’t execute transaction if you detect unusual signal
        ///- Please call 19009247 to check and handling.
        /// </summary>
        internal static string term_txt1 {
            get {
                return ResourceManager.GetString("term_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction of querying balance.
        /// </summary>
        internal static string vanTin_txt1 {
            get {
                return ResourceManager.GetString("vanTin_txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance of your account.
        /// </summary>
        internal static string vanTin_txt2 {
            get {
                return ResourceManager.GetString("vanTin_txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
